/**
 * Sync Live Activity bridge.
 *
 * Wraps expo-live-activity with a single-activity-at-a-time controller keyed
 * to the in-app sync lifecycle. The actual SwiftUI Lock Screen + Dynamic
 * Island layouts are auto-generated by the expo-live-activity config
 * plugin; we only push state through start / update / stop.
 *
 * Lifecycle:
 *   start  — when sync transitions from idle to running (BLE pull OR queue
 *            drain). Single activity per run; never two concurrent.
 *   update — on each progress / counts change while running.
 *   stop   — on terminal: synced_confirm, sync_error, or explicit cancel.
 *
 * The module is iOS-only and gracefully no-ops on Android, on iOS < 16.1,
 * and when the user disables Live Activities in Settings (the underlying
 * package returns void from startActivity in those cases).
 */

import { Platform } from "react-native"

// expo-live-activity ships a SwiftUI widget extension that needs its own
// signing identity at archive time. We don't have a beta-distribution
// story for the extension yet, so the plugin is removed from app.json
// and we require the JS bindings lazily — any call here is a no-op when
// the native module isn't linked. Re-enable by re-adding the plugin to
// app.json and running `expo prebuild --clean`.
type LiveActivityState = {
  title?: string
  subtitle?: string
  progressBar?: { progress: number }
}
type LiveActivityConfig = {
  deepLinkUrl?: string
  progressViewTint?: string
  timerType?: string
}
type LiveActivityModule = {
  startActivity: (s: LiveActivityState, c: LiveActivityConfig) => string | void
  updateActivity: (id: string, s: LiveActivityState) => void
  stopActivity: (id: string, s: LiveActivityState) => void
}
function loadNative(): LiveActivityModule | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require("expo-live-activity") as LiveActivityModule
  } catch {
    return null
  }
}
const native = loadNative()
const nativeStart = native?.startActivity
const nativeUpdate = native?.updateActivity
const nativeStop = native?.stopActivity

const DEEP_LINK = "hale://sync"

export type SyncActivityPayload = {
  title: string
  subtitle?: string
  /** 0..1, undefined = indeterminate */
  progress?: number
}

class SyncLiveActivityController {
  private currentId: string | null = null
  private supported = Platform.OS === "ios" && native != null

  start(p: SyncActivityPayload): void {
    if (!this.supported || !nativeStart) return
    if (this.currentId) {
      this.update(p)
      return
    }
    const state: LiveActivityState = {
      title: p.title,
      subtitle: p.subtitle,
      progressBar: p.progress != null ? { progress: p.progress } : undefined,
    }
    const config: LiveActivityConfig = {
      deepLinkUrl: DEEP_LINK,
      progressViewTint: "#0A84FF",
      timerType: "digital",
    }
    try {
      const id = nativeStart(state, config)
      if (typeof id === "string" && id.length > 0) this.currentId = id
    } catch (err) {
      console.warn("[live-activity] start failed", err)
    }
  }

  update(p: SyncActivityPayload): void {
    if (!this.supported || !nativeUpdate || !this.currentId) return
    const state: LiveActivityState = {
      title: p.title,
      subtitle: p.subtitle,
      progressBar: p.progress != null ? { progress: p.progress } : undefined,
    }
    try {
      nativeUpdate(this.currentId, state)
    } catch (err) {
      console.warn("[live-activity] update failed", err)
    }
  }

  /** Terminal state — Live Activity is dismissed after a short hold by iOS. */
  stop(p: SyncActivityPayload): void {
    if (!this.supported || !nativeStop || !this.currentId) return
    const state: LiveActivityState = {
      title: p.title,
      subtitle: p.subtitle,
      progressBar: p.progress != null ? { progress: p.progress } : { progress: 1 },
    }
    try {
      nativeStop(this.currentId, state)
    } catch (err) {
      console.warn("[live-activity] stop failed", err)
    } finally {
      this.currentId = null
    }
  }

  get isRunning(): boolean {
    return this.currentId != null
  }
}

export const syncLiveActivity = new SyncLiveActivityController()
