/**
 * Sync Live Activity bridge.
 *
 * Wraps expo-live-activity with a single-activity-at-a-time controller keyed
 * to the in-app sync lifecycle. The actual SwiftUI Lock Screen + Dynamic
 * Island layouts are auto-generated by the expo-live-activity config
 * plugin; we only push state through start / update / stop.
 *
 * Lifecycle:
 *   start  — when sync transitions from idle to running (BLE pull OR queue
 *            drain). Single activity per run; never two concurrent.
 *   update — on each progress / counts change while running.
 *   stop   — on terminal: synced_confirm, sync_error, or explicit cancel.
 *
 * The module is iOS-only and gracefully no-ops on Android, on iOS < 16.1,
 * and when the user disables Live Activities in Settings (the underlying
 * package returns void from startActivity in those cases).
 */

import { Platform } from "react-native"

import {
  startActivity as nativeStart,
  stopActivity as nativeStop,
  updateActivity as nativeUpdate,
  type LiveActivityState,
  type LiveActivityConfig,
} from "expo-live-activity"

const DEEP_LINK = "noop://sync"

export type SyncActivityPayload = {
  title: string
  subtitle?: string
  /** 0..1, undefined = indeterminate */
  progress?: number
}

class SyncLiveActivityController {
  private currentId: string | null = null
  private supported = Platform.OS === "ios"

  start(p: SyncActivityPayload): void {
    if (!this.supported) return
    if (this.currentId) {
      // Already running — treat as an update so we don't fork two activities.
      this.update(p)
      return
    }
    const state: LiveActivityState = {
      title: p.title,
      subtitle: p.subtitle,
      progressBar: p.progress != null ? { progress: p.progress } : undefined,
    }
    const config: LiveActivityConfig = {
      deepLinkUrl: DEEP_LINK,
      progressViewTint: "#0A84FF",
      timerType: "digital",
    }
    try {
      const id = nativeStart(state, config)
      if (typeof id === "string" && id.length > 0) this.currentId = id
    } catch (err) {
      console.warn("[live-activity] start failed", err)
    }
  }

  update(p: SyncActivityPayload): void {
    if (!this.supported || !this.currentId) return
    const state: LiveActivityState = {
      title: p.title,
      subtitle: p.subtitle,
      progressBar: p.progress != null ? { progress: p.progress } : undefined,
    }
    try {
      nativeUpdate(this.currentId, state)
    } catch (err) {
      console.warn("[live-activity] update failed", err)
    }
  }

  /** Terminal state — Live Activity is dismissed after a short hold by iOS. */
  stop(p: SyncActivityPayload): void {
    if (!this.supported || !this.currentId) return
    const state: LiveActivityState = {
      title: p.title,
      subtitle: p.subtitle,
      progressBar: p.progress != null ? { progress: p.progress } : { progress: 1 },
    }
    try {
      nativeStop(this.currentId, state)
    } catch (err) {
      console.warn("[live-activity] stop failed", err)
    } finally {
      this.currentId = null
    }
  }

  get isRunning(): boolean {
    return this.currentId != null
  }
}

export const syncLiveActivity = new SyncLiveActivityController()
