FROM rust:1.85-slim AS build
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY benches ./benches
RUN cargo build --release --bin noop-pipeline-worker

FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=build /app/target/release/noop-pipeline-worker /app
ENV PORT=8080
EXPOSE 8080
ENTRYPOINT ["/app"]
